<?php
/**
 * ConfigMediaPoolApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pbs\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ClientApi\Pbs\ApiException;
use ClientApi\Pbs\Configuration;
use ClientApi\Pbs\FormDataProcessor;
use ClientApi\Pbs\HeaderSelector;
use ClientApi\Pbs\ObjectSerializer;

/**
 * ConfigMediaPoolApi Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConfigMediaPoolApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'configMediaPoolCreateMediaPool' => [
            'application/json',
            'application/x-www-form-urlencoded',
        ],
        'configMediaPoolDeleteMediaPool' => [
            'application/json',
        ],
        'configMediaPoolGetConfigMediaPoolByName' => [
            'application/json',
        ],
        'configMediaPoolGetMediaPool' => [
            'application/json',
        ],
        'configMediaPoolUpdateMediaPool' => [
            'application/json',
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation configMediaPoolCreateMediaPool
     *
     * Create a new media pool
     *
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolRequest $config_media_pool_create_media_pool_request config_media_pool_create_media_pool_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolCreateMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configMediaPoolCreateMediaPool($config_media_pool_create_media_pool_request, string $contentType = self::contentTypes['configMediaPoolCreateMediaPool'][0])
    {
        list($response) = $this->configMediaPoolCreateMediaPoolWithHttpInfo($config_media_pool_create_media_pool_request, $contentType);
        return $response;
    }

    /**
     * Operation configMediaPoolCreateMediaPoolWithHttpInfo
     *
     * Create a new media pool
     *
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolRequest $config_media_pool_create_media_pool_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolCreateMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configMediaPoolCreateMediaPoolWithHttpInfo($config_media_pool_create_media_pool_request, string $contentType = self::contentTypes['configMediaPoolCreateMediaPool'][0])
    {
        $request = $this->configMediaPoolCreateMediaPoolRequest($config_media_pool_create_media_pool_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configMediaPoolCreateMediaPoolAsync
     *
     * Create a new media pool
     *
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolRequest $config_media_pool_create_media_pool_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolCreateMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolCreateMediaPoolAsync($config_media_pool_create_media_pool_request, string $contentType = self::contentTypes['configMediaPoolCreateMediaPool'][0])
    {
        return $this->configMediaPoolCreateMediaPoolAsyncWithHttpInfo($config_media_pool_create_media_pool_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configMediaPoolCreateMediaPoolAsyncWithHttpInfo
     *
     * Create a new media pool
     *
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolRequest $config_media_pool_create_media_pool_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolCreateMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolCreateMediaPoolAsyncWithHttpInfo($config_media_pool_create_media_pool_request, string $contentType = self::contentTypes['configMediaPoolCreateMediaPool'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolResponse';
        $request = $this->configMediaPoolCreateMediaPoolRequest($config_media_pool_create_media_pool_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configMediaPoolCreateMediaPool'
     *
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolCreateMediaPoolRequest $config_media_pool_create_media_pool_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolCreateMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configMediaPoolCreateMediaPoolRequest($config_media_pool_create_media_pool_request, string $contentType = self::contentTypes['configMediaPoolCreateMediaPool'][0])
    {

        // verify the required parameter 'config_media_pool_create_media_pool_request' is set
        if ($config_media_pool_create_media_pool_request === null || (is_array($config_media_pool_create_media_pool_request) && count($config_media_pool_create_media_pool_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $config_media_pool_create_media_pool_request when calling configMediaPoolCreateMediaPool'
            );
        }


        $resourcePath = '/config/media-pool';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($config_media_pool_create_media_pool_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($config_media_pool_create_media_pool_request));
            } else {
                $httpBody = $config_media_pool_create_media_pool_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configMediaPoolDeleteMediaPool
     *
     * Delete a media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolDeleteMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigMediaPoolDeleteMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configMediaPoolDeleteMediaPool($name, string $contentType = self::contentTypes['configMediaPoolDeleteMediaPool'][0])
    {
        list($response) = $this->configMediaPoolDeleteMediaPoolWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation configMediaPoolDeleteMediaPoolWithHttpInfo
     *
     * Delete a media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolDeleteMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigMediaPoolDeleteMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configMediaPoolDeleteMediaPoolWithHttpInfo($name, string $contentType = self::contentTypes['configMediaPoolDeleteMediaPool'][0])
    {
        $request = $this->configMediaPoolDeleteMediaPoolRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigMediaPoolDeleteMediaPoolResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigMediaPoolDeleteMediaPoolResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigMediaPoolDeleteMediaPoolResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configMediaPoolDeleteMediaPoolAsync
     *
     * Delete a media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolDeleteMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolDeleteMediaPoolAsync($name, string $contentType = self::contentTypes['configMediaPoolDeleteMediaPool'][0])
    {
        return $this->configMediaPoolDeleteMediaPoolAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configMediaPoolDeleteMediaPoolAsyncWithHttpInfo
     *
     * Delete a media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolDeleteMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolDeleteMediaPoolAsyncWithHttpInfo($name, string $contentType = self::contentTypes['configMediaPoolDeleteMediaPool'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigMediaPoolDeleteMediaPoolResponse';
        $request = $this->configMediaPoolDeleteMediaPoolRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configMediaPoolDeleteMediaPool'
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolDeleteMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configMediaPoolDeleteMediaPoolRequest($name, string $contentType = self::contentTypes['configMediaPoolDeleteMediaPool'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling configMediaPoolDeleteMediaPool'
            );
        }
        if (strlen($name) > 32) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigMediaPoolApi.configMediaPoolDeleteMediaPool, must be smaller than or equal to 32.');
        }
        if (strlen($name) < 2) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigMediaPoolApi.configMediaPoolDeleteMediaPool, must be bigger than or equal to 2.');
        }
        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $name)) {
            throw new \InvalidArgumentException("invalid value for \"name\" when calling ConfigMediaPoolApi.configMediaPoolDeleteMediaPool, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        

        $resourcePath = '/config/media-pool/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{name}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configMediaPoolGetConfigMediaPoolByName
     *
     * Get media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetConfigMediaPoolByName'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigMediaPoolGetConfigMediaPoolByNameResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configMediaPoolGetConfigMediaPoolByName($name, string $contentType = self::contentTypes['configMediaPoolGetConfigMediaPoolByName'][0])
    {
        list($response) = $this->configMediaPoolGetConfigMediaPoolByNameWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation configMediaPoolGetConfigMediaPoolByNameWithHttpInfo
     *
     * Get media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetConfigMediaPoolByName'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigMediaPoolGetConfigMediaPoolByNameResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configMediaPoolGetConfigMediaPoolByNameWithHttpInfo($name, string $contentType = self::contentTypes['configMediaPoolGetConfigMediaPoolByName'][0])
    {
        $request = $this->configMediaPoolGetConfigMediaPoolByNameRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigMediaPoolGetConfigMediaPoolByNameResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigMediaPoolGetConfigMediaPoolByNameResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigMediaPoolGetConfigMediaPoolByNameResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configMediaPoolGetConfigMediaPoolByNameAsync
     *
     * Get media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetConfigMediaPoolByName'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolGetConfigMediaPoolByNameAsync($name, string $contentType = self::contentTypes['configMediaPoolGetConfigMediaPoolByName'][0])
    {
        return $this->configMediaPoolGetConfigMediaPoolByNameAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configMediaPoolGetConfigMediaPoolByNameAsyncWithHttpInfo
     *
     * Get media pool configuration
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetConfigMediaPoolByName'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolGetConfigMediaPoolByNameAsyncWithHttpInfo($name, string $contentType = self::contentTypes['configMediaPoolGetConfigMediaPoolByName'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigMediaPoolGetConfigMediaPoolByNameResponse';
        $request = $this->configMediaPoolGetConfigMediaPoolByNameRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configMediaPoolGetConfigMediaPoolByName'
     *
     * @param  string $name Media pool name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetConfigMediaPoolByName'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configMediaPoolGetConfigMediaPoolByNameRequest($name, string $contentType = self::contentTypes['configMediaPoolGetConfigMediaPoolByName'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling configMediaPoolGetConfigMediaPoolByName'
            );
        }
        if (strlen($name) > 32) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigMediaPoolApi.configMediaPoolGetConfigMediaPoolByName, must be smaller than or equal to 32.');
        }
        if (strlen($name) < 2) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigMediaPoolApi.configMediaPoolGetConfigMediaPoolByName, must be bigger than or equal to 2.');
        }
        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $name)) {
            throw new \InvalidArgumentException("invalid value for \"name\" when calling ConfigMediaPoolApi.configMediaPoolGetConfigMediaPoolByName, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        

        $resourcePath = '/config/media-pool/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{name}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configMediaPoolGetMediaPool
     *
     * List media pools
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigMediaPoolGetMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configMediaPoolGetMediaPool(string $contentType = self::contentTypes['configMediaPoolGetMediaPool'][0])
    {
        list($response) = $this->configMediaPoolGetMediaPoolWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation configMediaPoolGetMediaPoolWithHttpInfo
     *
     * List media pools
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigMediaPoolGetMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configMediaPoolGetMediaPoolWithHttpInfo(string $contentType = self::contentTypes['configMediaPoolGetMediaPool'][0])
    {
        $request = $this->configMediaPoolGetMediaPoolRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigMediaPoolGetMediaPoolResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigMediaPoolGetMediaPoolResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigMediaPoolGetMediaPoolResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configMediaPoolGetMediaPoolAsync
     *
     * List media pools
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolGetMediaPoolAsync(string $contentType = self::contentTypes['configMediaPoolGetMediaPool'][0])
    {
        return $this->configMediaPoolGetMediaPoolAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configMediaPoolGetMediaPoolAsyncWithHttpInfo
     *
     * List media pools
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolGetMediaPoolAsyncWithHttpInfo(string $contentType = self::contentTypes['configMediaPoolGetMediaPool'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigMediaPoolGetMediaPoolResponse';
        $request = $this->configMediaPoolGetMediaPoolRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configMediaPoolGetMediaPool'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolGetMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configMediaPoolGetMediaPoolRequest(string $contentType = self::contentTypes['configMediaPoolGetMediaPool'][0])
    {


        $resourcePath = '/config/media-pool';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configMediaPoolUpdateMediaPool
     *
     * Update media pool settings
     *
     * @param  string $name Media pool name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolRequest|null $config_media_pool_update_media_pool_request config_media_pool_update_media_pool_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolUpdateMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configMediaPoolUpdateMediaPool($name, $config_media_pool_update_media_pool_request = null, string $contentType = self::contentTypes['configMediaPoolUpdateMediaPool'][0])
    {
        list($response) = $this->configMediaPoolUpdateMediaPoolWithHttpInfo($name, $config_media_pool_update_media_pool_request, $contentType);
        return $response;
    }

    /**
     * Operation configMediaPoolUpdateMediaPoolWithHttpInfo
     *
     * Update media pool settings
     *
     * @param  string $name Media pool name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolRequest|null $config_media_pool_update_media_pool_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolUpdateMediaPool'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configMediaPoolUpdateMediaPoolWithHttpInfo($name, $config_media_pool_update_media_pool_request = null, string $contentType = self::contentTypes['configMediaPoolUpdateMediaPool'][0])
    {
        $request = $this->configMediaPoolUpdateMediaPoolRequest($name, $config_media_pool_update_media_pool_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configMediaPoolUpdateMediaPoolAsync
     *
     * Update media pool settings
     *
     * @param  string $name Media pool name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolRequest|null $config_media_pool_update_media_pool_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolUpdateMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolUpdateMediaPoolAsync($name, $config_media_pool_update_media_pool_request = null, string $contentType = self::contentTypes['configMediaPoolUpdateMediaPool'][0])
    {
        return $this->configMediaPoolUpdateMediaPoolAsyncWithHttpInfo($name, $config_media_pool_update_media_pool_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configMediaPoolUpdateMediaPoolAsyncWithHttpInfo
     *
     * Update media pool settings
     *
     * @param  string $name Media pool name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolRequest|null $config_media_pool_update_media_pool_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolUpdateMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configMediaPoolUpdateMediaPoolAsyncWithHttpInfo($name, $config_media_pool_update_media_pool_request = null, string $contentType = self::contentTypes['configMediaPoolUpdateMediaPool'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolResponse';
        $request = $this->configMediaPoolUpdateMediaPoolRequest($name, $config_media_pool_update_media_pool_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configMediaPoolUpdateMediaPool'
     *
     * @param  string $name Media pool name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigMediaPoolUpdateMediaPoolRequest|null $config_media_pool_update_media_pool_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configMediaPoolUpdateMediaPool'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configMediaPoolUpdateMediaPoolRequest($name, $config_media_pool_update_media_pool_request = null, string $contentType = self::contentTypes['configMediaPoolUpdateMediaPool'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling configMediaPoolUpdateMediaPool'
            );
        }
        if (strlen($name) > 32) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigMediaPoolApi.configMediaPoolUpdateMediaPool, must be smaller than or equal to 32.');
        }
        if (strlen($name) < 2) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigMediaPoolApi.configMediaPoolUpdateMediaPool, must be bigger than or equal to 2.');
        }
        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $name)) {
            throw new \InvalidArgumentException("invalid value for \"name\" when calling ConfigMediaPoolApi.configMediaPoolUpdateMediaPool, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        


        $resourcePath = '/config/media-pool/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{name}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($config_media_pool_update_media_pool_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($config_media_pool_update_media_pool_request));
            } else {
                $httpBody = $config_media_pool_update_media_pool_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
