<?php
/**
 * ConfigDatastoreApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pbs\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ClientApi\Pbs\ApiException;
use ClientApi\Pbs\Configuration;
use ClientApi\Pbs\FormDataProcessor;
use ClientApi\Pbs\HeaderSelector;
use ClientApi\Pbs\ObjectSerializer;

/**
 * ConfigDatastoreApi Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConfigDatastoreApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'configDatastoreCreateDatastore' => [
            'application/json',
            'application/x-www-form-urlencoded',
        ],
        'configDatastoreDeleteDatastore' => [
            'application/json',
        ],
        'configDatastoreGetConfigDatastoreByName' => [
            'application/json',
        ],
        'configDatastoreGetDatastore' => [
            'application/json',
        ],
        'configDatastoreUpdateDatastore' => [
            'application/json',
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation configDatastoreCreateDatastore
     *
     * Create new datastore config
     *
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreRequest $config_datastore_create_datastore_request config_datastore_create_datastore_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreCreateDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configDatastoreCreateDatastore($config_datastore_create_datastore_request, string $contentType = self::contentTypes['configDatastoreCreateDatastore'][0])
    {
        list($response) = $this->configDatastoreCreateDatastoreWithHttpInfo($config_datastore_create_datastore_request, $contentType);
        return $response;
    }

    /**
     * Operation configDatastoreCreateDatastoreWithHttpInfo
     *
     * Create new datastore config
     *
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreRequest $config_datastore_create_datastore_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreCreateDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configDatastoreCreateDatastoreWithHttpInfo($config_datastore_create_datastore_request, string $contentType = self::contentTypes['configDatastoreCreateDatastore'][0])
    {
        $request = $this->configDatastoreCreateDatastoreRequest($config_datastore_create_datastore_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configDatastoreCreateDatastoreAsync
     *
     * Create new datastore config
     *
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreRequest $config_datastore_create_datastore_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreCreateDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreCreateDatastoreAsync($config_datastore_create_datastore_request, string $contentType = self::contentTypes['configDatastoreCreateDatastore'][0])
    {
        return $this->configDatastoreCreateDatastoreAsyncWithHttpInfo($config_datastore_create_datastore_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configDatastoreCreateDatastoreAsyncWithHttpInfo
     *
     * Create new datastore config
     *
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreRequest $config_datastore_create_datastore_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreCreateDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreCreateDatastoreAsyncWithHttpInfo($config_datastore_create_datastore_request, string $contentType = self::contentTypes['configDatastoreCreateDatastore'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreResponse';
        $request = $this->configDatastoreCreateDatastoreRequest($config_datastore_create_datastore_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configDatastoreCreateDatastore'
     *
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreCreateDatastoreRequest $config_datastore_create_datastore_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreCreateDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configDatastoreCreateDatastoreRequest($config_datastore_create_datastore_request, string $contentType = self::contentTypes['configDatastoreCreateDatastore'][0])
    {

        // verify the required parameter 'config_datastore_create_datastore_request' is set
        if ($config_datastore_create_datastore_request === null || (is_array($config_datastore_create_datastore_request) && count($config_datastore_create_datastore_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $config_datastore_create_datastore_request when calling configDatastoreCreateDatastore'
            );
        }


        $resourcePath = '/config/datastore';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($config_datastore_create_datastore_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($config_datastore_create_datastore_request));
            } else {
                $httpBody = $config_datastore_create_datastore_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configDatastoreDeleteDatastore
     *
     * Remove a datastore configuration and optionally delete all its contents
     *
     * @param  string $name Datastore name. (required)
     * @param  bool|null $destroy_data Delete the datastore&#39;s underlying contents (optional, default to 0)
     * @param  string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @param  bool|null $keep_job_configs If enabled, the job configurations related to this datastore will be kept. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreDeleteDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigDatastoreDeleteDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configDatastoreDeleteDatastore($name, $destroy_data = 0, $digest = null, $keep_job_configs = 0, string $contentType = self::contentTypes['configDatastoreDeleteDatastore'][0])
    {
        list($response) = $this->configDatastoreDeleteDatastoreWithHttpInfo($name, $destroy_data, $digest, $keep_job_configs, $contentType);
        return $response;
    }

    /**
     * Operation configDatastoreDeleteDatastoreWithHttpInfo
     *
     * Remove a datastore configuration and optionally delete all its contents
     *
     * @param  string $name Datastore name. (required)
     * @param  bool|null $destroy_data Delete the datastore&#39;s underlying contents (optional, default to 0)
     * @param  string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @param  bool|null $keep_job_configs If enabled, the job configurations related to this datastore will be kept. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreDeleteDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigDatastoreDeleteDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configDatastoreDeleteDatastoreWithHttpInfo($name, $destroy_data = 0, $digest = null, $keep_job_configs = 0, string $contentType = self::contentTypes['configDatastoreDeleteDatastore'][0])
    {
        $request = $this->configDatastoreDeleteDatastoreRequest($name, $destroy_data, $digest, $keep_job_configs, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigDatastoreDeleteDatastoreResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigDatastoreDeleteDatastoreResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigDatastoreDeleteDatastoreResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configDatastoreDeleteDatastoreAsync
     *
     * Remove a datastore configuration and optionally delete all its contents
     *
     * @param  string $name Datastore name. (required)
     * @param  bool|null $destroy_data Delete the datastore&#39;s underlying contents (optional, default to 0)
     * @param  string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @param  bool|null $keep_job_configs If enabled, the job configurations related to this datastore will be kept. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreDeleteDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreDeleteDatastoreAsync($name, $destroy_data = 0, $digest = null, $keep_job_configs = 0, string $contentType = self::contentTypes['configDatastoreDeleteDatastore'][0])
    {
        return $this->configDatastoreDeleteDatastoreAsyncWithHttpInfo($name, $destroy_data, $digest, $keep_job_configs, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configDatastoreDeleteDatastoreAsyncWithHttpInfo
     *
     * Remove a datastore configuration and optionally delete all its contents
     *
     * @param  string $name Datastore name. (required)
     * @param  bool|null $destroy_data Delete the datastore&#39;s underlying contents (optional, default to 0)
     * @param  string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @param  bool|null $keep_job_configs If enabled, the job configurations related to this datastore will be kept. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreDeleteDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreDeleteDatastoreAsyncWithHttpInfo($name, $destroy_data = 0, $digest = null, $keep_job_configs = 0, string $contentType = self::contentTypes['configDatastoreDeleteDatastore'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigDatastoreDeleteDatastoreResponse';
        $request = $this->configDatastoreDeleteDatastoreRequest($name, $destroy_data, $digest, $keep_job_configs, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configDatastoreDeleteDatastore'
     *
     * @param  string $name Datastore name. (required)
     * @param  bool|null $destroy_data Delete the datastore&#39;s underlying contents (optional, default to 0)
     * @param  string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications. (optional)
     * @param  bool|null $keep_job_configs If enabled, the job configurations related to this datastore will be kept. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreDeleteDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configDatastoreDeleteDatastoreRequest($name, $destroy_data = 0, $digest = null, $keep_job_configs = 0, string $contentType = self::contentTypes['configDatastoreDeleteDatastore'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling configDatastoreDeleteDatastore'
            );
        }
        if (strlen($name) > 32) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigDatastoreApi.configDatastoreDeleteDatastore, must be smaller than or equal to 32.');
        }
        if (strlen($name) < 3) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigDatastoreApi.configDatastoreDeleteDatastore, must be bigger than or equal to 3.');
        }
        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $name)) {
            throw new \InvalidArgumentException("invalid value for \"name\" when calling ConfigDatastoreApi.configDatastoreDeleteDatastore, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        

        if ($digest !== null && !preg_match("/^[a-f0-9]{64}$/", $digest)) {
            throw new \InvalidArgumentException("invalid value for \"digest\" when calling ConfigDatastoreApi.configDatastoreDeleteDatastore, must conform to the pattern /^[a-f0-9]{64}$/.");
        }
        


        $resourcePath = '/config/datastore/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $destroy_data,
            'destroy-data', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $digest,
            'digest', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $keep_job_configs,
            'keep-job-configs', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{name}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configDatastoreGetConfigDatastoreByName
     *
     * Read a datastore configuration
     *
     * @param  string $name Datastore name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetConfigDatastoreByName'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigDatastoreGetConfigDatastoreByNameResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configDatastoreGetConfigDatastoreByName($name, string $contentType = self::contentTypes['configDatastoreGetConfigDatastoreByName'][0])
    {
        list($response) = $this->configDatastoreGetConfigDatastoreByNameWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation configDatastoreGetConfigDatastoreByNameWithHttpInfo
     *
     * Read a datastore configuration
     *
     * @param  string $name Datastore name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetConfigDatastoreByName'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigDatastoreGetConfigDatastoreByNameResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configDatastoreGetConfigDatastoreByNameWithHttpInfo($name, string $contentType = self::contentTypes['configDatastoreGetConfigDatastoreByName'][0])
    {
        $request = $this->configDatastoreGetConfigDatastoreByNameRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigDatastoreGetConfigDatastoreByNameResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigDatastoreGetConfigDatastoreByNameResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigDatastoreGetConfigDatastoreByNameResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configDatastoreGetConfigDatastoreByNameAsync
     *
     * Read a datastore configuration
     *
     * @param  string $name Datastore name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetConfigDatastoreByName'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreGetConfigDatastoreByNameAsync($name, string $contentType = self::contentTypes['configDatastoreGetConfigDatastoreByName'][0])
    {
        return $this->configDatastoreGetConfigDatastoreByNameAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configDatastoreGetConfigDatastoreByNameAsyncWithHttpInfo
     *
     * Read a datastore configuration
     *
     * @param  string $name Datastore name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetConfigDatastoreByName'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreGetConfigDatastoreByNameAsyncWithHttpInfo($name, string $contentType = self::contentTypes['configDatastoreGetConfigDatastoreByName'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigDatastoreGetConfigDatastoreByNameResponse';
        $request = $this->configDatastoreGetConfigDatastoreByNameRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configDatastoreGetConfigDatastoreByName'
     *
     * @param  string $name Datastore name. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetConfigDatastoreByName'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configDatastoreGetConfigDatastoreByNameRequest($name, string $contentType = self::contentTypes['configDatastoreGetConfigDatastoreByName'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling configDatastoreGetConfigDatastoreByName'
            );
        }
        if (strlen($name) > 32) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigDatastoreApi.configDatastoreGetConfigDatastoreByName, must be smaller than or equal to 32.');
        }
        if (strlen($name) < 3) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigDatastoreApi.configDatastoreGetConfigDatastoreByName, must be bigger than or equal to 3.');
        }
        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $name)) {
            throw new \InvalidArgumentException("invalid value for \"name\" when calling ConfigDatastoreApi.configDatastoreGetConfigDatastoreByName, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        

        $resourcePath = '/config/datastore/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{name}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configDatastoreGetDatastore
     *
     * List all datastores
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigDatastoreGetDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configDatastoreGetDatastore(string $contentType = self::contentTypes['configDatastoreGetDatastore'][0])
    {
        list($response) = $this->configDatastoreGetDatastoreWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation configDatastoreGetDatastoreWithHttpInfo
     *
     * List all datastores
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigDatastoreGetDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configDatastoreGetDatastoreWithHttpInfo(string $contentType = self::contentTypes['configDatastoreGetDatastore'][0])
    {
        $request = $this->configDatastoreGetDatastoreRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigDatastoreGetDatastoreResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigDatastoreGetDatastoreResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigDatastoreGetDatastoreResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configDatastoreGetDatastoreAsync
     *
     * List all datastores
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreGetDatastoreAsync(string $contentType = self::contentTypes['configDatastoreGetDatastore'][0])
    {
        return $this->configDatastoreGetDatastoreAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configDatastoreGetDatastoreAsyncWithHttpInfo
     *
     * List all datastores
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreGetDatastoreAsyncWithHttpInfo(string $contentType = self::contentTypes['configDatastoreGetDatastore'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigDatastoreGetDatastoreResponse';
        $request = $this->configDatastoreGetDatastoreRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configDatastoreGetDatastore'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreGetDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configDatastoreGetDatastoreRequest(string $contentType = self::contentTypes['configDatastoreGetDatastore'][0])
    {


        $resourcePath = '/config/datastore';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation configDatastoreUpdateDatastore
     *
     * Update datastore config
     *
     * @param  string $name Datastore name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreRequest|null $config_datastore_update_datastore_request config_datastore_update_datastore_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreUpdateDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError
     */
    public function configDatastoreUpdateDatastore($name, $config_datastore_update_datastore_request = null, string $contentType = self::contentTypes['configDatastoreUpdateDatastore'][0])
    {
        list($response) = $this->configDatastoreUpdateDatastoreWithHttpInfo($name, $config_datastore_update_datastore_request, $contentType);
        return $response;
    }

    /**
     * Operation configDatastoreUpdateDatastoreWithHttpInfo
     *
     * Update datastore config
     *
     * @param  string $name Datastore name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreRequest|null $config_datastore_update_datastore_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreUpdateDatastore'] to see the possible values for this operation
     *
     * @throws \ClientApi\Pbs\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreResponse|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError|\ClientApi\Pbs\Model\PbsError, HTTP status code, HTTP response headers (array of strings)
     */
    public function configDatastoreUpdateDatastoreWithHttpInfo($name, $config_datastore_update_datastore_request = null, string $contentType = self::contentTypes['configDatastoreUpdateDatastore'][0])
    {
        $request = $this->configDatastoreUpdateDatastoreRequest($name, $config_datastore_update_datastore_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 501:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\ClientApi\Pbs\Model\PbsError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 501:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientApi\Pbs\Model\PbsError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation configDatastoreUpdateDatastoreAsync
     *
     * Update datastore config
     *
     * @param  string $name Datastore name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreRequest|null $config_datastore_update_datastore_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreUpdateDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreUpdateDatastoreAsync($name, $config_datastore_update_datastore_request = null, string $contentType = self::contentTypes['configDatastoreUpdateDatastore'][0])
    {
        return $this->configDatastoreUpdateDatastoreAsyncWithHttpInfo($name, $config_datastore_update_datastore_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation configDatastoreUpdateDatastoreAsyncWithHttpInfo
     *
     * Update datastore config
     *
     * @param  string $name Datastore name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreRequest|null $config_datastore_update_datastore_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreUpdateDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function configDatastoreUpdateDatastoreAsyncWithHttpInfo($name, $config_datastore_update_datastore_request = null, string $contentType = self::contentTypes['configDatastoreUpdateDatastore'][0])
    {
        $returnType = '\ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreResponse';
        $request = $this->configDatastoreUpdateDatastoreRequest($name, $config_datastore_update_datastore_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'configDatastoreUpdateDatastore'
     *
     * @param  string $name Datastore name. (required)
     * @param  \ClientApi\Pbs\Model\ConfigDatastoreUpdateDatastoreRequest|null $config_datastore_update_datastore_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['configDatastoreUpdateDatastore'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function configDatastoreUpdateDatastoreRequest($name, $config_datastore_update_datastore_request = null, string $contentType = self::contentTypes['configDatastoreUpdateDatastore'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling configDatastoreUpdateDatastore'
            );
        }
        if (strlen($name) > 32) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigDatastoreApi.configDatastoreUpdateDatastore, must be smaller than or equal to 32.');
        }
        if (strlen($name) < 3) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling ConfigDatastoreApi.configDatastoreUpdateDatastore, must be bigger than or equal to 3.');
        }
        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $name)) {
            throw new \InvalidArgumentException("invalid value for \"name\" when calling ConfigDatastoreApi.configDatastoreUpdateDatastore, must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }
        


        $resourcePath = '/config/datastore/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{name}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($config_datastore_update_datastore_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($config_datastore_update_datastore_request));
            } else {
                $httpBody = $config_datastore_update_datastore_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('CSRFPreventionToken');
        if ($apiKey !== null) {
            $headers['CSRFPreventionToken'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
