<?php
/**
 * AdminDatastoreGetStatusResponseDataGcStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pbs\Model;

use \ArrayAccess;
use \ClientApi\Pbs\ObjectSerializer;

/**
 * AdminDatastoreGetStatusResponseDataGcStatus Class Doc Comment
 *
 * @category Class
 * @description Garbage collection status.
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdminDatastoreGetStatusResponseDataGcStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AdminDatastoreGetStatusResponse_data_gc_status';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'cache_stats' => '\ClientApi\Pbs\Model\AdminDatastoreGetGcResponseDataCacheStats',
        'disk_bytes' => 'int',
        'disk_chunks' => 'int',
        'index_data_bytes' => 'int',
        'index_file_count' => 'int',
        'pending_bytes' => 'int',
        'pending_chunks' => 'int',
        'removed_bad' => 'int',
        'removed_bytes' => 'int',
        'removed_chunks' => 'int',
        'still_bad' => 'int',
        'upid' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'cache_stats' => null,
        'disk_bytes' => 'int64',
        'disk_chunks' => 'int64',
        'index_data_bytes' => 'int64',
        'index_file_count' => 'int64',
        'pending_bytes' => 'int64',
        'pending_chunks' => 'int64',
        'removed_bad' => 'int64',
        'removed_bytes' => 'int64',
        'removed_chunks' => 'int64',
        'still_bad' => 'int64',
        'upid' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'cache_stats' => false,
        'disk_bytes' => false,
        'disk_chunks' => false,
        'index_data_bytes' => false,
        'index_file_count' => false,
        'pending_bytes' => false,
        'pending_chunks' => false,
        'removed_bad' => false,
        'removed_bytes' => false,
        'removed_chunks' => false,
        'still_bad' => false,
        'upid' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cache_stats' => 'cache-stats',
        'disk_bytes' => 'disk-bytes',
        'disk_chunks' => 'disk-chunks',
        'index_data_bytes' => 'index-data-bytes',
        'index_file_count' => 'index-file-count',
        'pending_bytes' => 'pending-bytes',
        'pending_chunks' => 'pending-chunks',
        'removed_bad' => 'removed-bad',
        'removed_bytes' => 'removed-bytes',
        'removed_chunks' => 'removed-chunks',
        'still_bad' => 'still-bad',
        'upid' => 'upid',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cache_stats' => 'setCacheStats',
        'disk_bytes' => 'setDiskBytes',
        'disk_chunks' => 'setDiskChunks',
        'index_data_bytes' => 'setIndexDataBytes',
        'index_file_count' => 'setIndexFileCount',
        'pending_bytes' => 'setPendingBytes',
        'pending_chunks' => 'setPendingChunks',
        'removed_bad' => 'setRemovedBad',
        'removed_bytes' => 'setRemovedBytes',
        'removed_chunks' => 'setRemovedChunks',
        'still_bad' => 'setStillBad',
        'upid' => 'setUpid',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cache_stats' => 'getCacheStats',
        'disk_bytes' => 'getDiskBytes',
        'disk_chunks' => 'getDiskChunks',
        'index_data_bytes' => 'getIndexDataBytes',
        'index_file_count' => 'getIndexFileCount',
        'pending_bytes' => 'getPendingBytes',
        'pending_chunks' => 'getPendingChunks',
        'removed_bad' => 'getRemovedBad',
        'removed_bytes' => 'getRemovedBytes',
        'removed_chunks' => 'getRemovedChunks',
        'still_bad' => 'getStillBad',
        'upid' => 'getUpid',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('cache_stats', $data ?? [], null);
        
        $this->setIfExists('disk_bytes', $data ?? [], null);
        
        $this->setIfExists('disk_chunks', $data ?? [], null);
        
        $this->setIfExists('index_data_bytes', $data ?? [], null);
        
        $this->setIfExists('index_file_count', $data ?? [], null);
        
        $this->setIfExists('pending_bytes', $data ?? [], null);
        
        $this->setIfExists('pending_chunks', $data ?? [], null);
        
        $this->setIfExists('removed_bad', $data ?? [], null);
        
        $this->setIfExists('removed_bytes', $data ?? [], null);
        
        $this->setIfExists('removed_chunks', $data ?? [], null);
        
        $this->setIfExists('still_bad', $data ?? [], null);
        
        $this->setIfExists('upid', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        if ($this->container['disk_bytes'] === null) {
            $invalidProperties[] = "'disk_bytes' can't be null";
        }
        if (($this->container['disk_bytes'] < 0)) {
            $invalidProperties[] = "invalid value for 'disk_bytes', must be bigger than or equal to 0.";
        }

        
        if ($this->container['disk_chunks'] === null) {
            $invalidProperties[] = "'disk_chunks' can't be null";
        }
        if (($this->container['disk_chunks'] < 0)) {
            $invalidProperties[] = "invalid value for 'disk_chunks', must be bigger than or equal to 0.";
        }

        
        if ($this->container['index_data_bytes'] === null) {
            $invalidProperties[] = "'index_data_bytes' can't be null";
        }
        if (($this->container['index_data_bytes'] < 0)) {
            $invalidProperties[] = "invalid value for 'index_data_bytes', must be bigger than or equal to 0.";
        }

        
        if ($this->container['index_file_count'] === null) {
            $invalidProperties[] = "'index_file_count' can't be null";
        }
        if (($this->container['index_file_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'index_file_count', must be bigger than or equal to 0.";
        }

        
        if ($this->container['pending_bytes'] === null) {
            $invalidProperties[] = "'pending_bytes' can't be null";
        }
        if (($this->container['pending_bytes'] < 0)) {
            $invalidProperties[] = "invalid value for 'pending_bytes', must be bigger than or equal to 0.";
        }

        
        if ($this->container['pending_chunks'] === null) {
            $invalidProperties[] = "'pending_chunks' can't be null";
        }
        if (($this->container['pending_chunks'] < 0)) {
            $invalidProperties[] = "invalid value for 'pending_chunks', must be bigger than or equal to 0.";
        }

        
        if ($this->container['removed_bad'] === null) {
            $invalidProperties[] = "'removed_bad' can't be null";
        }
        if (($this->container['removed_bad'] < 0)) {
            $invalidProperties[] = "invalid value for 'removed_bad', must be bigger than or equal to 0.";
        }

        
        if ($this->container['removed_bytes'] === null) {
            $invalidProperties[] = "'removed_bytes' can't be null";
        }
        if (($this->container['removed_bytes'] < 0)) {
            $invalidProperties[] = "invalid value for 'removed_bytes', must be bigger than or equal to 0.";
        }

        
        if ($this->container['removed_chunks'] === null) {
            $invalidProperties[] = "'removed_chunks' can't be null";
        }
        if (($this->container['removed_chunks'] < 0)) {
            $invalidProperties[] = "invalid value for 'removed_chunks', must be bigger than or equal to 0.";
        }

        
        if ($this->container['still_bad'] === null) {
            $invalidProperties[] = "'still_bad' can't be null";
        }
        if (($this->container['still_bad'] < 0)) {
            $invalidProperties[] = "invalid value for 'still_bad', must be bigger than or equal to 0.";
        }

        
        if (!is_null($this->container['upid']) && (mb_strlen($this->container['upid']) < 36)) {
            $invalidProperties[] = "invalid value for 'upid', the character length must be bigger than or equal to 36.";
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets cache_stats
     *
     * @return \ClientApi\Pbs\Model\AdminDatastoreGetGcResponseDataCacheStats|null
     */
    public function getCacheStats()
    {
        return $this->container['cache_stats'];
    }

    /**
     * Sets cache_stats
     *
     * @param \ClientApi\Pbs\Model\AdminDatastoreGetGcResponseDataCacheStats|null $cache_stats cache_stats
     *
     * @return self
     */
    public function setCacheStats($cache_stats)
    {
        if (is_null($cache_stats)) {
            throw new \InvalidArgumentException('non-nullable cache_stats cannot be null');
        }
        $this->container['cache_stats'] = $cache_stats;

        return $this;
    }
    

    /**
     * Gets disk_bytes
     *
     * @return int
     */
    public function getDiskBytes()
    {
        return $this->container['disk_bytes'];
    }

    /**
     * Sets disk_bytes
     *
     * @param int $disk_bytes Bytes used on disk.
     *
     * @return self
     */
    public function setDiskBytes($disk_bytes)
    {
        if (is_null($disk_bytes)) {
            throw new \InvalidArgumentException('non-nullable disk_bytes cannot be null');
        }

        if (($disk_bytes < 0)) {
            throw new \InvalidArgumentException('invalid value for $disk_bytes when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['disk_bytes'] = $disk_bytes;

        return $this;
    }
    

    /**
     * Gets disk_chunks
     *
     * @return int
     */
    public function getDiskChunks()
    {
        return $this->container['disk_chunks'];
    }

    /**
     * Sets disk_chunks
     *
     * @param int $disk_chunks Chunks used on disk.
     *
     * @return self
     */
    public function setDiskChunks($disk_chunks)
    {
        if (is_null($disk_chunks)) {
            throw new \InvalidArgumentException('non-nullable disk_chunks cannot be null');
        }

        if (($disk_chunks < 0)) {
            throw new \InvalidArgumentException('invalid value for $disk_chunks when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['disk_chunks'] = $disk_chunks;

        return $this;
    }
    

    /**
     * Gets index_data_bytes
     *
     * @return int
     */
    public function getIndexDataBytes()
    {
        return $this->container['index_data_bytes'];
    }

    /**
     * Sets index_data_bytes
     *
     * @param int $index_data_bytes Sum of bytes referred by index files.
     *
     * @return self
     */
    public function setIndexDataBytes($index_data_bytes)
    {
        if (is_null($index_data_bytes)) {
            throw new \InvalidArgumentException('non-nullable index_data_bytes cannot be null');
        }

        if (($index_data_bytes < 0)) {
            throw new \InvalidArgumentException('invalid value for $index_data_bytes when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['index_data_bytes'] = $index_data_bytes;

        return $this;
    }
    

    /**
     * Gets index_file_count
     *
     * @return int
     */
    public function getIndexFileCount()
    {
        return $this->container['index_file_count'];
    }

    /**
     * Sets index_file_count
     *
     * @param int $index_file_count Number of processed index files.
     *
     * @return self
     */
    public function setIndexFileCount($index_file_count)
    {
        if (is_null($index_file_count)) {
            throw new \InvalidArgumentException('non-nullable index_file_count cannot be null');
        }

        if (($index_file_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $index_file_count when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['index_file_count'] = $index_file_count;

        return $this;
    }
    

    /**
     * Gets pending_bytes
     *
     * @return int
     */
    public function getPendingBytes()
    {
        return $this->container['pending_bytes'];
    }

    /**
     * Sets pending_bytes
     *
     * @param int $pending_bytes Sum of pending bytes (pending removal - kept for safety).
     *
     * @return self
     */
    public function setPendingBytes($pending_bytes)
    {
        if (is_null($pending_bytes)) {
            throw new \InvalidArgumentException('non-nullable pending_bytes cannot be null');
        }

        if (($pending_bytes < 0)) {
            throw new \InvalidArgumentException('invalid value for $pending_bytes when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['pending_bytes'] = $pending_bytes;

        return $this;
    }
    

    /**
     * Gets pending_chunks
     *
     * @return int
     */
    public function getPendingChunks()
    {
        return $this->container['pending_chunks'];
    }

    /**
     * Sets pending_chunks
     *
     * @param int $pending_chunks Number of pending chunks (pending removal - kept for safety).
     *
     * @return self
     */
    public function setPendingChunks($pending_chunks)
    {
        if (is_null($pending_chunks)) {
            throw new \InvalidArgumentException('non-nullable pending_chunks cannot be null');
        }

        if (($pending_chunks < 0)) {
            throw new \InvalidArgumentException('invalid value for $pending_chunks when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['pending_chunks'] = $pending_chunks;

        return $this;
    }
    

    /**
     * Gets removed_bad
     *
     * @return int
     */
    public function getRemovedBad()
    {
        return $this->container['removed_bad'];
    }

    /**
     * Sets removed_bad
     *
     * @param int $removed_bad Number of chunks marked as .bad by verify that have been removed by GC.
     *
     * @return self
     */
    public function setRemovedBad($removed_bad)
    {
        if (is_null($removed_bad)) {
            throw new \InvalidArgumentException('non-nullable removed_bad cannot be null');
        }

        if (($removed_bad < 0)) {
            throw new \InvalidArgumentException('invalid value for $removed_bad when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['removed_bad'] = $removed_bad;

        return $this;
    }
    

    /**
     * Gets removed_bytes
     *
     * @return int
     */
    public function getRemovedBytes()
    {
        return $this->container['removed_bytes'];
    }

    /**
     * Sets removed_bytes
     *
     * @param int $removed_bytes Sum of removed bytes.
     *
     * @return self
     */
    public function setRemovedBytes($removed_bytes)
    {
        if (is_null($removed_bytes)) {
            throw new \InvalidArgumentException('non-nullable removed_bytes cannot be null');
        }

        if (($removed_bytes < 0)) {
            throw new \InvalidArgumentException('invalid value for $removed_bytes when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['removed_bytes'] = $removed_bytes;

        return $this;
    }
    

    /**
     * Gets removed_chunks
     *
     * @return int
     */
    public function getRemovedChunks()
    {
        return $this->container['removed_chunks'];
    }

    /**
     * Sets removed_chunks
     *
     * @param int $removed_chunks Number of removed chunks.
     *
     * @return self
     */
    public function setRemovedChunks($removed_chunks)
    {
        if (is_null($removed_chunks)) {
            throw new \InvalidArgumentException('non-nullable removed_chunks cannot be null');
        }

        if (($removed_chunks < 0)) {
            throw new \InvalidArgumentException('invalid value for $removed_chunks when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['removed_chunks'] = $removed_chunks;

        return $this;
    }
    

    /**
     * Gets still_bad
     *
     * @return int
     */
    public function getStillBad()
    {
        return $this->container['still_bad'];
    }

    /**
     * Sets still_bad
     *
     * @param int $still_bad Number of chunks still marked as .bad after garbage collection.
     *
     * @return self
     */
    public function setStillBad($still_bad)
    {
        if (is_null($still_bad)) {
            throw new \InvalidArgumentException('non-nullable still_bad cannot be null');
        }

        if (($still_bad < 0)) {
            throw new \InvalidArgumentException('invalid value for $still_bad when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 0.');
        }

        $this->container['still_bad'] = $still_bad;

        return $this;
    }
    

    /**
     * Gets upid
     *
     * @return string|null
     */
    public function getUpid()
    {
        return $this->container['upid'];
    }

    /**
     * Sets upid
     *
     * @param string|null $upid Unique Process/Task Identifier
     *
     * @return self
     */
    public function setUpid($upid)
    {
        if (is_null($upid)) {
            throw new \InvalidArgumentException('non-nullable upid cannot be null');
        }

        if ((mb_strlen($upid) < 36)) {
            throw new \InvalidArgumentException('invalid length for $upid when calling AdminDatastoreGetStatusResponseDataGcStatus., must be bigger than or equal to 36.');
        }

        $this->container['upid'] = $upid;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



