<?php
/**
 * ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pbs\Model;

use \ArrayAccess;
use \ClientApi\Pbs\ObjectSerializer;

/**
 * ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'digest' => 'string',
        'force' => 'bool',
        'hint' => 'string',
        'kdf' => '\ClientApi\Pbs\Model\PbsKdfEnum',
        'new_password' => 'string',
        'password' => 'string',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'digest' => null,
        'force' => null,
        'hint' => null,
        'kdf' => null,
        'new_password' => null,
        'password' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'digest' => false,
        'force' => false,
        'hint' => false,
        'kdf' => false,
        'new_password' => false,
        'password' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'digest' => 'digest',
        'force' => 'force',
        'hint' => 'hint',
        'kdf' => 'kdf',
        'new_password' => 'new-password',
        'password' => 'password',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'digest' => 'setDigest',
        'force' => 'setForce',
        'hint' => 'setHint',
        'kdf' => 'setKdf',
        'new_password' => 'setNewPassword',
        'password' => 'setPassword',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'digest' => 'getDigest',
        'force' => 'getForce',
        'hint' => 'getHint',
        'kdf' => 'getKdf',
        'new_password' => 'getNewPassword',
        'password' => 'getPassword',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('digest', $data ?? [], null);
        
        $this->setIfExists('force', $data ?? [], 0);
        
        $this->setIfExists('hint', $data ?? [], null);
        
        $this->setIfExists('kdf', $data ?? [], PbsKdfEnum::SCRYPT);
        
        $this->setIfExists('new_password', $data ?? [], null);
        
        $this->setIfExists('password', $data ?? [], null);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        if (!is_null($this->container['digest']) && !preg_match("/^[a-f0-9]{64}$/", $this->container['digest'])) {
            $invalidProperties[] = "invalid value for 'digest', must be conform to the pattern /^[a-f0-9]{64}$/.";
        }

        
        
        if ($this->container['hint'] === null) {
            $invalidProperties[] = "'hint' can't be null";
        }
        if ((mb_strlen($this->container['hint']) > 64)) {
            $invalidProperties[] = "invalid value for 'hint', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['hint']) < 1)) {
            $invalidProperties[] = "invalid value for 'hint', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[[:^cntrl:]]*$/", $this->container['hint'])) {
            $invalidProperties[] = "invalid value for 'hint', must be conform to the pattern /^[[:^cntrl:]]*$/.";
        }

        
        
        if ($this->container['new_password'] === null) {
            $invalidProperties[] = "'new_password' can't be null";
        }
        if ((mb_strlen($this->container['new_password']) < 5)) {
            $invalidProperties[] = "invalid value for 'new_password', the character length must be bigger than or equal to 5.";
        }

        
        if (!is_null($this->container['password']) && (mb_strlen($this->container['password']) < 5)) {
            $invalidProperties[] = "invalid value for 'password', the character length must be bigger than or equal to 5.";
        }

        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets digest
     *
     * @return string|null
     */
    public function getDigest()
    {
        return $this->container['digest'];
    }

    /**
     * Sets digest
     *
     * @param string|null $digest Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
     *
     * @return self
     */
    public function setDigest($digest)
    {
        if (is_null($digest)) {
            throw new \InvalidArgumentException('non-nullable digest cannot be null');
        }

        if ((!preg_match("/^[a-f0-9]{64}$/", ObjectSerializer::toString($digest)))) {
            throw new \InvalidArgumentException("invalid value for \$digest when calling ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest., must conform to the pattern /^[a-f0-9]{64}$/.");
        }

        $this->container['digest'] = $digest;

        return $this;
    }
    

    /**
     * Gets force
     *
     * @return bool|null
     */
    public function getForce()
    {
        return $this->container['force'];
    }

    /**
     * Sets force
     *
     * @param bool|null $force Reset the passphrase for a tape key, using the root-only accessible copy.
     *
     * @return self
     */
    public function setForce($force)
    {
        if (is_null($force)) {
            throw new \InvalidArgumentException('non-nullable force cannot be null');
        }
        $this->container['force'] = $force;

        return $this;
    }
    

    /**
     * Gets hint
     *
     * @return string
     */
    public function getHint()
    {
        return $this->container['hint'];
    }

    /**
     * Sets hint
     *
     * @param string $hint Password hint.
     *
     * @return self
     */
    public function setHint($hint)
    {
        if (is_null($hint)) {
            throw new \InvalidArgumentException('non-nullable hint cannot be null');
        }
        if ((mb_strlen($hint) > 64)) {
            throw new \InvalidArgumentException('invalid length for $hint when calling ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($hint) < 1)) {
            throw new \InvalidArgumentException('invalid length for $hint when calling ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[[:^cntrl:]]*$/", ObjectSerializer::toString($hint)))) {
            throw new \InvalidArgumentException("invalid value for \$hint when calling ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest., must conform to the pattern /^[[:^cntrl:]]*$/.");
        }

        $this->container['hint'] = $hint;

        return $this;
    }
    

    /**
     * Gets kdf
     *
     * @return \ClientApi\Pbs\Model\PbsKdfEnum|null
     */
    public function getKdf()
    {
        return $this->container['kdf'];
    }

    /**
     * Sets kdf
     *
     * @param \ClientApi\Pbs\Model\PbsKdfEnum|null $kdf Key derivation function for password protected encryption keys.
     *
     * @return self
     */
    public function setKdf($kdf)
    {
        if (is_null($kdf)) {
            throw new \InvalidArgumentException('non-nullable kdf cannot be null');
        }
        $this->container['kdf'] = $kdf;

        return $this;
    }
    

    /**
     * Gets new_password
     *
     * @return string
     */
    public function getNewPassword()
    {
        return $this->container['new_password'];
    }

    /**
     * Sets new_password
     *
     * @param string $new_password The new password.
     *
     * @return self
     */
    public function setNewPassword($new_password)
    {
        if (is_null($new_password)) {
            throw new \InvalidArgumentException('non-nullable new_password cannot be null');
        }

        if ((mb_strlen($new_password) < 5)) {
            throw new \InvalidArgumentException('invalid length for $new_password when calling ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest., must be bigger than or equal to 5.');
        }

        $this->container['new_password'] = $new_password;

        return $this;
    }
    

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password The current password.
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }

        if ((mb_strlen($password) < 5)) {
            throw new \InvalidArgumentException('invalid length for $password when calling ConfigTapeEncryptionKeysUpdateTapeEncryptionKeysRequest., must be bigger than or equal to 5.');
        }

        $this->container['password'] = $password;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



