<?php
/**
 * NodesDisksCreateDirectoryRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pbs\Model;

use \ArrayAccess;
use \ClientApi\Pbs\ObjectSerializer;

/**
 * NodesDisksCreateDirectoryRequest Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NodesDisksCreateDirectoryRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'NodesDisksCreateDirectoryRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'add_datastore' => 'bool',
        'disk' => 'string',
        'filesystem' => '\ClientApi\Pbs\Model\PbsFilesystemEnum',
        'name' => 'string',
        'removable_datastore' => 'bool',
        
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'add_datastore' => null,
        'disk' => null,
        'filesystem' => null,
        'name' => null,
        'removable_datastore' => null,
        
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'add_datastore' => false,
        'disk' => false,
        'filesystem' => false,
        'name' => false,
        'removable_datastore' => false,
        
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'add_datastore' => 'add-datastore',
        'disk' => 'disk',
        'filesystem' => 'filesystem',
        'name' => 'name',
        'removable_datastore' => 'removable-datastore',
        
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'add_datastore' => 'setAddDatastore',
        'disk' => 'setDisk',
        'filesystem' => 'setFilesystem',
        'name' => 'setName',
        'removable_datastore' => 'setRemovableDatastore',
        
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'add_datastore' => 'getAddDatastore',
        'disk' => 'getDisk',
        'filesystem' => 'getFilesystem',
        'name' => 'getName',
        'removable_datastore' => 'getRemovableDatastore',
        
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        
        $this->setIfExists('add_datastore', $data ?? [], 0);
        
        $this->setIfExists('disk', $data ?? [], null);
        
        $this->setIfExists('filesystem', $data ?? [], null);
        
        $this->setIfExists('name', $data ?? [], null);
        
        $this->setIfExists('removable_datastore', $data ?? [], 0);
        

    }


    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        
        
        if ($this->container['disk'] === null) {
            $invalidProperties[] = "'disk' can't be null";
        }
        if ((mb_strlen($this->container['disk']) > 64)) {
            $invalidProperties[] = "invalid value for 'disk', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen($this->container['disk']) < 3)) {
            $invalidProperties[] = "invalid value for 'disk', the character length must be bigger than or equal to 3.";
        }

        if (!preg_match("/^(?:(?:h|s|x?v)d[a-z]+)|(?:nvme\\d+n\\d+)$/", $this->container['disk'])) {
            $invalidProperties[] = "invalid value for 'disk', must be conform to the pattern /^(?:(?:h|s|x?v)d[a-z]+)|(?:nvme\\d+n\\d+)$/.";
        }

        
        
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 32)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 32.";
        }

        if ((mb_strlen($this->container['name']) < 3)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 3.";
        }

        if (!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", $this->container['name'])) {
            $invalidProperties[] = "invalid value for 'name', must be conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.";
        }

        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    

    /**
     * Gets add_datastore
     *
     * @return bool|null
     */
    public function getAddDatastore()
    {
        return $this->container['add_datastore'];
    }

    /**
     * Sets add_datastore
     *
     * @param bool|null $add_datastore Configure a datastore using the directory.
     *
     * @return self
     */
    public function setAddDatastore($add_datastore)
    {
        if (is_null($add_datastore)) {
            throw new \InvalidArgumentException('non-nullable add_datastore cannot be null');
        }
        $this->container['add_datastore'] = $add_datastore;

        return $this;
    }
    

    /**
     * Gets disk
     *
     * @return string
     */
    public function getDisk()
    {
        return $this->container['disk'];
    }

    /**
     * Sets disk
     *
     * @param string $disk Block device name (/sys/block/<name>).
     *
     * @return self
     */
    public function setDisk($disk)
    {
        if (is_null($disk)) {
            throw new \InvalidArgumentException('non-nullable disk cannot be null');
        }
        if ((mb_strlen($disk) > 64)) {
            throw new \InvalidArgumentException('invalid length for $disk when calling NodesDisksCreateDirectoryRequest., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($disk) < 3)) {
            throw new \InvalidArgumentException('invalid length for $disk when calling NodesDisksCreateDirectoryRequest., must be bigger than or equal to 3.');
        }
        if ((!preg_match("/^(?:(?:h|s|x?v)d[a-z]+)|(?:nvme\\d+n\\d+)$/", ObjectSerializer::toString($disk)))) {
            throw new \InvalidArgumentException("invalid value for \$disk when calling NodesDisksCreateDirectoryRequest., must conform to the pattern /^(?:(?:h|s|x?v)d[a-z]+)|(?:nvme\\d+n\\d+)$/.");
        }

        $this->container['disk'] = $disk;

        return $this;
    }
    

    /**
     * Gets filesystem
     *
     * @return \ClientApi\Pbs\Model\PbsFilesystemEnum|null
     */
    public function getFilesystem()
    {
        return $this->container['filesystem'];
    }

    /**
     * Sets filesystem
     *
     * @param \ClientApi\Pbs\Model\PbsFilesystemEnum|null $filesystem A file system type supported by our tooling.
     *
     * @return self
     */
    public function setFilesystem($filesystem)
    {
        if (is_null($filesystem)) {
            throw new \InvalidArgumentException('non-nullable filesystem cannot be null');
        }
        $this->container['filesystem'] = $filesystem;

        return $this;
    }
    

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Datastore name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 32)) {
            throw new \InvalidArgumentException('invalid length for $name when calling NodesDisksCreateDirectoryRequest., must be smaller than or equal to 32.');
        }
        if ((mb_strlen($name) < 3)) {
            throw new \InvalidArgumentException('invalid length for $name when calling NodesDisksCreateDirectoryRequest., must be bigger than or equal to 3.');
        }
        if ((!preg_match("/^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/", ObjectSerializer::toString($name)))) {
            throw new \InvalidArgumentException("invalid value for \$name when calling NodesDisksCreateDirectoryRequest., must conform to the pattern /^(?:[A-Za-z0-9_][A-Za-z0-9._\\-]*)$/.");
        }

        $this->container['name'] = $name;

        return $this;
    }
    

    /**
     * Gets removable_datastore
     *
     * @return bool|null
     */
    public function getRemovableDatastore()
    {
        return $this->container['removable_datastore'];
    }

    /**
     * Sets removable_datastore
     *
     * @param bool|null $removable_datastore The added datastore is removable.
     *
     * @return self
     */
    public function setRemovableDatastore($removable_datastore)
    {
        if (is_null($removable_datastore)) {
            throw new \InvalidArgumentException('non-nullable removable_datastore cannot be null');
        }
        $this->container['removable_datastore'] = $removable_datastore;

        return $this;
    }
    



    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        $out = ObjectSerializer::sanitizeForSerialization($this);


        return $out;
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}



