<?php
/**
 * PbsTapeDriveDensityEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Proxmox Backup Server API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pbs.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientApi\Pbs\Model;
use \ClientApi\Pbs\ObjectSerializer;

/**
 * PbsTapeDriveDensityEnum Class Doc Comment
 *
 * @category Class
 * @package  ClientApi\Pbs
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PbsTapeDriveDensityEnum
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const LTO1 = 'LTO1';

    public const LTO2 = 'LTO2';

    public const LTO3 = 'LTO3';

    public const LTO4 = 'LTO4';

    public const LTO5 = 'LTO5';

    public const LTO6 = 'LTO6';

    public const LTO7 = 'LTO7';

    public const LTO7_M8 = 'LTO7M8';

    public const LTO8 = 'LTO8';

    public const LTO9 = 'LTO9';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::LTO1,
            self::LTO2,
            self::LTO3,
            self::LTO4,
            self::LTO5,
            self::LTO6,
            self::LTO7,
            self::LTO7_M8,
            self::LTO8,
            self::LTO9
        ];
    }
}


